name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Prettier Check
      run: npm run prettier -- --check

    - name: Run Tests
      run: npm test
